/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GdkPixbuf *main_window_icon_pixbuf;
  GtkWidget *main_vbox;
  GtkWidget *main_notebook;
  GtkWidget *link_frame;
  GtkWidget *link_alignment;
  GtkWidget *link_table;
  GtkWidget *entry_status;
  GtkWidget *entry_bssid;
  GtkWidget *entry_ssid;
  GtkWidget *entry_channel;
  GtkWidget *label_bssid;
  GtkWidget *label_status;
  GtkWidget *label_ssid;
  GtkWidget *label_channel;
  GtkWidget *hbox_txrate;
  GtkWidget *frame_rate_1;
  GtkWidget *eventbox_rate_1;
  GtkWidget *label_rate_1;
  GtkWidget *frame_rate_2;
  GtkWidget *eventbox_rate_2;
  GtkWidget *label_rate_2;
  GtkWidget *frame_rate_5;
  GtkWidget *eventbox_rate_5;
  GtkWidget *label_rate_5;
  GtkWidget *frame_rate_11;
  GtkWidget *eventbox_rate_11;
  GtkWidget *label_rate_11;
  GtkWidget *frame_rate_22;
  GtkWidget *eventbox_rate_22;
  GtkWidget *label_rate_22;
  GtkWidget *label_txrate;
  GtkWidget *link_label;
  GtkWidget *label_tab_link;
  GtkWidget *signal_frame;
  GtkWidget *signal_alignment;
  GtkWidget *signal_vbox;
  GtkWidget *quality_vbox;
  GtkWidget *quality_hbox;
  GtkWidget *quality_label;
  GtkWidget *quality_progressbar;
  GtkWidget *strength_vbox;
  GtkWidget *strength_hbox;
  GtkWidget *strength_label;
  GtkWidget *strength_label_sep;
  GtkWidget *strength_entry;
  GtkWidget *strength_label_avg;
  GtkWidget *strength_entry_avg;
  GtkWidget *strength_label_max;
  GtkWidget *strength_entry_max;
  GtkWidget *strength_progressbar;
  GtkWidget *noise_vbox;
  GtkWidget *noise_hbox;
  GtkWidget *noise_label;
  GtkWidget *noise_label_sep;
  GtkWidget *noise_entry;
  GtkWidget *noise_label_avg;
  GtkWidget *noise_entry_avg;
  GtkWidget *noise_label_max;
  GtkWidget *noise_entry_max;
  GtkWidget *noise_progressbar;
  GtkWidget *signal_label;
  GtkWidget *label_tab_signal;
  GtkWidget *signal_history_frame;
  GtkWidget *signal_history_alignment;
  GtkWidget *signal_databox;
  GtkWidget *signal_history_label;
  GtkWidget *label_tab_signal_history;
  GtkWidget *traffic_frame;
  GtkWidget *traffic_alignment;
  GtkWidget *traffic_vbox;
  GtkWidget *transmit_vbox;
  GtkWidget *transmit_hbox;
  GtkWidget *transmit_label;
  GtkWidget *transmit_label_sep;
  GtkWidget *transmit_entry;
  GtkWidget *transmit_progressbar;
  GtkWidget *receive_vbox;
  GtkWidget *receive_hbox;
  GtkWidget *receive_label;
  GtkWidget *receive_label_sep;
  GtkWidget *receive_entry;
  GtkWidget *receive_progressbar;
  GtkWidget *traffic_label;
  GtkWidget *label_tab_traffic;
  GtkWidget *traffic_history_frame;
  GtkWidget *traffic_history_alignment;
  GtkWidget *traffic_databox;
  GtkWidget *traffic_history_label;
  GtkWidget *label_tab_traffic_history;
  GtkWidget *settings_frame;
  GtkWidget *settings_alignment;
  GtkWidget *settings_hbox;
  GtkWidget *vbox_settings_controls;
  GtkWidget *checkbutton_rate;
  GtkWidget *table_settings;
  GtkWidget *vbox16;
  GtkWidget *hbox11;
  GtkWidget *label6;
  GtkWidget *hscale_channel;
  GtkWidget *vbox17;
  GtkWidget *hbox12;
  GtkWidget *label7;
  GtkWidget *hscale_packets;
  GtkWidget *vbox18;
  GtkWidget *hbox13;
  GtkWidget *label8;
  GtkWidget *hscale_seconds_min;
  GtkWidget *vbox19;
  GtkWidget *hbox14;
  GtkWidget *label9;
  GtkWidget *hscale_seconds_max;
  GtkWidget *alignment3;
  GtkObject *spinbutton_packets_adj;
  GtkWidget *spinbutton_packets;
  GtkWidget *alignment4;
  GtkObject *spinbutton_seconds_min_adj;
  GtkWidget *spinbutton_seconds_min;
  GtkWidget *alignment5;
  GtkObject *spinbutton_seconds_max_adj;
  GtkWidget *spinbutton_seconds_max;
  GtkWidget *alignment_channel;
  GtkObject *spinbutton_channel_adj;
  GtkWidget *spinbutton_channel;
  GtkWidget *vbox_settings_buttons;
  GtkWidget *label_button_space;
  GtkWidget *button_apply;
  GtkWidget *button_cancel;
  GtkWidget *settings_label;
  GtkWidget *label_tab_settings;
  GtkWidget *about_vbox;
  GtkWidget *about_image;
  GtkWidget *label_about_title;
  GtkWidget *label_about_info;
  GtkWidget *label_about_copyright;
  GtkWidget *label_tab_about;
  GtkWidget *main_hpaned;
  GtkWidget *device_statusbar;
  GtkWidget *hpaned1;
  GtkWidget *main_statusbar;
  GtkWidget *user_statusbar;

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (main_window, "main_window");
  gtk_window_set_title (GTK_WINDOW (main_window), _("GTK ACX Tool"));
  gtk_window_set_position (GTK_WINDOW (main_window), GTK_WIN_POS_CENTER);
  main_window_icon_pixbuf = create_pixbuf ("gacxtool.png");
  if (main_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (main_window), main_window_icon_pixbuf);
      gdk_pixbuf_unref (main_window_icon_pixbuf);
    }

  main_vbox = gtk_vbox_new (FALSE, 1);
  gtk_widget_set_name (main_vbox, "main_vbox");
  gtk_widget_show (main_vbox);
  gtk_container_add (GTK_CONTAINER (main_window), main_vbox);

  main_notebook = gtk_notebook_new ();
  gtk_widget_set_name (main_notebook, "main_notebook");
  gtk_widget_show (main_notebook);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_notebook, TRUE, TRUE, 0);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (main_notebook), GTK_POS_LEFT);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (main_notebook), TRUE);
  gtk_notebook_popup_enable (GTK_NOTEBOOK (main_notebook));

  link_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (link_frame, "link_frame");
  gtk_widget_show (link_frame);
  gtk_container_add (GTK_CONTAINER (main_notebook), link_frame);

  link_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (link_alignment, "link_alignment");
  gtk_widget_show (link_alignment);
  gtk_container_add (GTK_CONTAINER (link_frame), link_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (link_alignment), 0, 0, 12, 0);

  link_table = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (link_table, "link_table");
  gtk_widget_show (link_table);
  gtk_container_add (GTK_CONTAINER (link_alignment), link_table);
  gtk_container_set_border_width (GTK_CONTAINER (link_table), 2);
  gtk_table_set_row_spacings (GTK_TABLE (link_table), 2);
  gtk_table_set_col_spacings (GTK_TABLE (link_table), 2);

  entry_status = gtk_entry_new ();
  gtk_widget_set_name (entry_status, "entry_status");
  gtk_widget_show (entry_status);
  gtk_table_attach (GTK_TABLE (link_table), entry_status, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry_status), FALSE);

  entry_bssid = gtk_entry_new ();
  gtk_widget_set_name (entry_bssid, "entry_bssid");
  gtk_widget_show (entry_bssid);
  gtk_table_attach (GTK_TABLE (link_table), entry_bssid, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry_bssid), FALSE);

  entry_ssid = gtk_entry_new ();
  gtk_widget_set_name (entry_ssid, "entry_ssid");
  gtk_widget_show (entry_ssid);
  gtk_table_attach (GTK_TABLE (link_table), entry_ssid, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry_ssid), FALSE);

  entry_channel = gtk_entry_new ();
  gtk_widget_set_name (entry_channel, "entry_channel");
  gtk_widget_show (entry_channel);
  gtk_table_attach (GTK_TABLE (link_table), entry_channel, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry_channel), FALSE);

  label_bssid = gtk_label_new (_("BSSID"));
  gtk_widget_set_name (label_bssid, "label_bssid");
  gtk_widget_show (label_bssid);
  gtk_table_attach (GTK_TABLE (link_table), label_bssid, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_bssid), 0, 0.5);

  label_status = gtk_label_new (_("Status"));
  gtk_widget_set_name (label_status, "label_status");
  gtk_widget_show (label_status);
  gtk_table_attach (GTK_TABLE (link_table), label_status, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_status), 0, 0.5);

  label_ssid = gtk_label_new (_("SSID"));
  gtk_widget_set_name (label_ssid, "label_ssid");
  gtk_widget_show (label_ssid);
  gtk_table_attach (GTK_TABLE (link_table), label_ssid, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_ssid), 0, 0.5);

  label_channel = gtk_label_new (_("Channel"));
  gtk_widget_set_name (label_channel, "label_channel");
  gtk_widget_show (label_channel);
  gtk_table_attach (GTK_TABLE (link_table), label_channel, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_channel), 0, 0.5);

  hbox_txrate = gtk_hbox_new (TRUE, 1);
  gtk_widget_set_name (hbox_txrate, "hbox_txrate");
  gtk_widget_show (hbox_txrate);
  gtk_table_attach (GTK_TABLE (link_table), hbox_txrate, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  frame_rate_1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_rate_1, "frame_rate_1");
  gtk_widget_show (frame_rate_1);
  gtk_box_pack_start (GTK_BOX (hbox_txrate), frame_rate_1, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_rate_1), GTK_SHADOW_ETCHED_OUT);

  eventbox_rate_1 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox_rate_1, "eventbox_rate_1");
  gtk_widget_show (eventbox_rate_1);
  gtk_container_add (GTK_CONTAINER (frame_rate_1), eventbox_rate_1);

  label_rate_1 = gtk_label_new (_("<b>1</b>"));
  gtk_widget_set_name (label_rate_1, "label_rate_1");
  gtk_widget_show (label_rate_1);
  gtk_container_add (GTK_CONTAINER (eventbox_rate_1), label_rate_1);
  gtk_label_set_use_markup (GTK_LABEL (label_rate_1), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_rate_1), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label_rate_1), TRUE);

  frame_rate_2 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_rate_2, "frame_rate_2");
  gtk_widget_show (frame_rate_2);
  gtk_box_pack_start (GTK_BOX (hbox_txrate), frame_rate_2, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_rate_2), GTK_SHADOW_ETCHED_OUT);

  eventbox_rate_2 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox_rate_2, "eventbox_rate_2");
  gtk_widget_show (eventbox_rate_2);
  gtk_container_add (GTK_CONTAINER (frame_rate_2), eventbox_rate_2);

  label_rate_2 = gtk_label_new (_("<b>2</b>"));
  gtk_widget_set_name (label_rate_2, "label_rate_2");
  gtk_widget_show (label_rate_2);
  gtk_container_add (GTK_CONTAINER (eventbox_rate_2), label_rate_2);
  gtk_label_set_use_markup (GTK_LABEL (label_rate_2), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_rate_2), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label_rate_2), TRUE);

  frame_rate_5 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_rate_5, "frame_rate_5");
  gtk_widget_show (frame_rate_5);
  gtk_box_pack_start (GTK_BOX (hbox_txrate), frame_rate_5, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_rate_5), GTK_SHADOW_ETCHED_OUT);

  eventbox_rate_5 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox_rate_5, "eventbox_rate_5");
  gtk_widget_show (eventbox_rate_5);
  gtk_container_add (GTK_CONTAINER (frame_rate_5), eventbox_rate_5);

  label_rate_5 = gtk_label_new (_("<b>5.5</b>"));
  gtk_widget_set_name (label_rate_5, "label_rate_5");
  gtk_widget_show (label_rate_5);
  gtk_container_add (GTK_CONTAINER (eventbox_rate_5), label_rate_5);
  gtk_label_set_use_markup (GTK_LABEL (label_rate_5), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_rate_5), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label_rate_5), TRUE);

  frame_rate_11 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_rate_11, "frame_rate_11");
  gtk_widget_show (frame_rate_11);
  gtk_box_pack_start (GTK_BOX (hbox_txrate), frame_rate_11, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_rate_11), GTK_SHADOW_ETCHED_OUT);

  eventbox_rate_11 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox_rate_11, "eventbox_rate_11");
  gtk_widget_show (eventbox_rate_11);
  gtk_container_add (GTK_CONTAINER (frame_rate_11), eventbox_rate_11);

  label_rate_11 = gtk_label_new (_("<b>11</b>"));
  gtk_widget_set_name (label_rate_11, "label_rate_11");
  gtk_widget_show (label_rate_11);
  gtk_container_add (GTK_CONTAINER (eventbox_rate_11), label_rate_11);
  gtk_label_set_use_markup (GTK_LABEL (label_rate_11), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_rate_11), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label_rate_11), TRUE);

  frame_rate_22 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame_rate_22, "frame_rate_22");
  gtk_widget_show (frame_rate_22);
  gtk_box_pack_start (GTK_BOX (hbox_txrate), frame_rate_22, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_rate_22), GTK_SHADOW_ETCHED_OUT);

  eventbox_rate_22 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox_rate_22, "eventbox_rate_22");
  gtk_widget_show (eventbox_rate_22);
  gtk_container_add (GTK_CONTAINER (frame_rate_22), eventbox_rate_22);

  label_rate_22 = gtk_label_new (_("<b>22</b>"));
  gtk_widget_set_name (label_rate_22, "label_rate_22");
  gtk_widget_show (label_rate_22);
  gtk_container_add (GTK_CONTAINER (eventbox_rate_22), label_rate_22);
  gtk_label_set_use_markup (GTK_LABEL (label_rate_22), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_rate_22), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label_rate_22), TRUE);

  label_txrate = gtk_label_new (_("TxRate"));
  gtk_widget_set_name (label_txrate, "label_txrate");
  gtk_widget_show (label_txrate);
  gtk_table_attach (GTK_TABLE (link_table), label_txrate, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_txrate), 0, 0.5);

  link_label = gtk_label_new (_("<b>Link Info.</b>"));
  gtk_widget_set_name (link_label, "link_label");
  gtk_widget_show (link_label);
  gtk_frame_set_label_widget (GTK_FRAME (link_frame), link_label);
  gtk_label_set_use_markup (GTK_LABEL (link_label), TRUE);

  label_tab_link = gtk_label_new (_("Link"));
  gtk_widget_set_name (label_tab_link, "label_tab_link");
  gtk_widget_show (label_tab_link);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 0), label_tab_link);

  signal_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (signal_frame, "signal_frame");
  gtk_widget_show (signal_frame);
  gtk_container_add (GTK_CONTAINER (main_notebook), signal_frame);

  signal_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (signal_alignment, "signal_alignment");
  gtk_widget_show (signal_alignment);
  gtk_container_add (GTK_CONTAINER (signal_frame), signal_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (signal_alignment), 0, 0, 12, 0);

  signal_vbox = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (signal_vbox, "signal_vbox");
  gtk_widget_show (signal_vbox);
  gtk_container_add (GTK_CONTAINER (signal_alignment), signal_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (signal_vbox), 2);

  quality_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (quality_vbox, "quality_vbox");
  gtk_widget_show (quality_vbox);
  gtk_box_pack_start (GTK_BOX (signal_vbox), quality_vbox, TRUE, FALSE, 0);

  quality_hbox = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (quality_hbox, "quality_hbox");
  gtk_widget_show (quality_hbox);
  gtk_box_pack_start (GTK_BOX (quality_vbox), quality_hbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (quality_hbox), 2);

  quality_label = gtk_label_new (_("Link Quality"));
  gtk_widget_set_name (quality_label, "quality_label");
  gtk_widget_show (quality_label);
  gtk_box_pack_start (GTK_BOX (quality_hbox), quality_label, FALSE, FALSE, 0);

  quality_progressbar = gtk_progress_bar_new ();
  gtk_widget_set_name (quality_progressbar, "quality_progressbar");
  gtk_widget_show (quality_progressbar);
  gtk_box_pack_start (GTK_BOX (quality_vbox), quality_progressbar, FALSE, FALSE, 0);
  gtk_progress_bar_set_pulse_step (GTK_PROGRESS_BAR (quality_progressbar), 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (quality_progressbar), _("0 %"));

  strength_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (strength_vbox, "strength_vbox");
  gtk_widget_show (strength_vbox);
  gtk_box_pack_start (GTK_BOX (signal_vbox), strength_vbox, TRUE, FALSE, 0);

  strength_hbox = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (strength_hbox, "strength_hbox");
  gtk_widget_show (strength_hbox);
  gtk_box_pack_start (GTK_BOX (strength_vbox), strength_hbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (strength_hbox), 2);

  strength_label = gtk_label_new (_("Signal Strength"));
  gtk_widget_set_name (strength_label, "strength_label");
  gtk_widget_show (strength_label);
  gtk_box_pack_start (GTK_BOX (strength_hbox), strength_label, FALSE, FALSE, 0);

  strength_label_sep = gtk_label_new ("");
  gtk_widget_set_name (strength_label_sep, "strength_label_sep");
  gtk_widget_show (strength_label_sep);
  gtk_box_pack_start (GTK_BOX (strength_hbox), strength_label_sep, TRUE, TRUE, 0);

  strength_entry = gtk_entry_new ();
  gtk_widget_set_name (strength_entry, "strength_entry");
  gtk_widget_show (strength_entry);
  gtk_box_pack_start (GTK_BOX (strength_hbox), strength_entry, FALSE, FALSE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (strength_entry), 3);
  gtk_editable_set_editable (GTK_EDITABLE (strength_entry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (strength_entry), _("0"));
  gtk_entry_set_has_frame (GTK_ENTRY (strength_entry), FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (strength_entry), 3);

  strength_label_avg = gtk_label_new (_("avg:"));
  gtk_widget_set_name (strength_label_avg, "strength_label_avg");
  gtk_widget_show (strength_label_avg);
  gtk_box_pack_start (GTK_BOX (strength_hbox), strength_label_avg, FALSE, FALSE, 0);

  strength_entry_avg = gtk_entry_new ();
  gtk_widget_set_name (strength_entry_avg, "strength_entry_avg");
  gtk_widget_show (strength_entry_avg);
  gtk_box_pack_start (GTK_BOX (strength_hbox), strength_entry_avg, FALSE, FALSE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (strength_entry_avg), 3);
  gtk_editable_set_editable (GTK_EDITABLE (strength_entry_avg), FALSE);
  gtk_entry_set_text (GTK_ENTRY (strength_entry_avg), _("0"));
  gtk_entry_set_has_frame (GTK_ENTRY (strength_entry_avg), FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (strength_entry_avg), 3);

  strength_label_max = gtk_label_new (_("max:"));
  gtk_widget_set_name (strength_label_max, "strength_label_max");
  gtk_widget_show (strength_label_max);
  gtk_box_pack_start (GTK_BOX (strength_hbox), strength_label_max, FALSE, FALSE, 0);

  strength_entry_max = gtk_entry_new ();
  gtk_widget_set_name (strength_entry_max, "strength_entry_max");
  gtk_widget_show (strength_entry_max);
  gtk_box_pack_start (GTK_BOX (strength_hbox), strength_entry_max, FALSE, FALSE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (strength_entry_max), 3);
  gtk_editable_set_editable (GTK_EDITABLE (strength_entry_max), FALSE);
  gtk_entry_set_text (GTK_ENTRY (strength_entry_max), _("0"));
  gtk_entry_set_has_frame (GTK_ENTRY (strength_entry_max), FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (strength_entry_max), 3);

  strength_progressbar = gtk_progress_bar_new ();
  gtk_widget_set_name (strength_progressbar, "strength_progressbar");
  gtk_widget_show (strength_progressbar);
  gtk_box_pack_start (GTK_BOX (strength_vbox), strength_progressbar, FALSE, FALSE, 0);
  gtk_progress_bar_set_pulse_step (GTK_PROGRESS_BAR (strength_progressbar), 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (strength_progressbar), _("0 %"));

  noise_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (noise_vbox, "noise_vbox");
  gtk_widget_show (noise_vbox);
  gtk_box_pack_start (GTK_BOX (signal_vbox), noise_vbox, TRUE, FALSE, 0);

  noise_hbox = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (noise_hbox, "noise_hbox");
  gtk_widget_show (noise_hbox);
  gtk_box_pack_start (GTK_BOX (noise_vbox), noise_hbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (noise_hbox), 2);

  noise_label = gtk_label_new (_("Noise Level"));
  gtk_widget_set_name (noise_label, "noise_label");
  gtk_widget_show (noise_label);
  gtk_box_pack_start (GTK_BOX (noise_hbox), noise_label, FALSE, FALSE, 0);

  noise_label_sep = gtk_label_new ("");
  gtk_widget_set_name (noise_label_sep, "noise_label_sep");
  gtk_widget_show (noise_label_sep);
  gtk_box_pack_start (GTK_BOX (noise_hbox), noise_label_sep, TRUE, TRUE, 0);

  noise_entry = gtk_entry_new ();
  gtk_widget_set_name (noise_entry, "noise_entry");
  gtk_widget_show (noise_entry);
  gtk_box_pack_start (GTK_BOX (noise_hbox), noise_entry, FALSE, FALSE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (noise_entry), 3);
  gtk_editable_set_editable (GTK_EDITABLE (noise_entry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (noise_entry), _("0"));
  gtk_entry_set_has_frame (GTK_ENTRY (noise_entry), FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (noise_entry), 3);

  noise_label_avg = gtk_label_new (_("avg:"));
  gtk_widget_set_name (noise_label_avg, "noise_label_avg");
  gtk_widget_show (noise_label_avg);
  gtk_box_pack_start (GTK_BOX (noise_hbox), noise_label_avg, FALSE, FALSE, 0);

  noise_entry_avg = gtk_entry_new ();
  gtk_widget_set_name (noise_entry_avg, "noise_entry_avg");
  gtk_widget_show (noise_entry_avg);
  gtk_box_pack_start (GTK_BOX (noise_hbox), noise_entry_avg, FALSE, FALSE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (noise_entry_avg), 3);
  gtk_editable_set_editable (GTK_EDITABLE (noise_entry_avg), FALSE);
  gtk_entry_set_text (GTK_ENTRY (noise_entry_avg), _("0"));
  gtk_entry_set_has_frame (GTK_ENTRY (noise_entry_avg), FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (noise_entry_avg), 3);

  noise_label_max = gtk_label_new (_("max:"));
  gtk_widget_set_name (noise_label_max, "noise_label_max");
  gtk_widget_show (noise_label_max);
  gtk_box_pack_start (GTK_BOX (noise_hbox), noise_label_max, FALSE, FALSE, 0);

  noise_entry_max = gtk_entry_new ();
  gtk_widget_set_name (noise_entry_max, "noise_entry_max");
  gtk_widget_show (noise_entry_max);
  gtk_box_pack_start (GTK_BOX (noise_hbox), noise_entry_max, FALSE, FALSE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (noise_entry_max), 3);
  gtk_editable_set_editable (GTK_EDITABLE (noise_entry_max), FALSE);
  gtk_entry_set_text (GTK_ENTRY (noise_entry_max), _("0"));
  gtk_entry_set_has_frame (GTK_ENTRY (noise_entry_max), FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (noise_entry_max), 3);

  noise_progressbar = gtk_progress_bar_new ();
  gtk_widget_set_name (noise_progressbar, "noise_progressbar");
  gtk_widget_show (noise_progressbar);
  gtk_box_pack_start (GTK_BOX (noise_vbox), noise_progressbar, FALSE, FALSE, 0);
  gtk_progress_bar_set_pulse_step (GTK_PROGRESS_BAR (noise_progressbar), 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (noise_progressbar), _("0 %"));

  signal_label = gtk_label_new (_("<b>Link Quality/Signal Strength</b>"));
  gtk_widget_set_name (signal_label, "signal_label");
  gtk_widget_show (signal_label);
  gtk_frame_set_label_widget (GTK_FRAME (signal_frame), signal_label);
  gtk_label_set_use_markup (GTK_LABEL (signal_label), TRUE);

  label_tab_signal = gtk_label_new (_("Signal"));
  gtk_widget_set_name (label_tab_signal, "label_tab_signal");
  gtk_widget_show (label_tab_signal);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 1), label_tab_signal);

  signal_history_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (signal_history_frame, "signal_history_frame");
  gtk_widget_show (signal_history_frame);
  gtk_container_add (GTK_CONTAINER (main_notebook), signal_history_frame);

  signal_history_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (signal_history_alignment, "signal_history_alignment");
  gtk_widget_show (signal_history_alignment);
  gtk_container_add (GTK_CONTAINER (signal_history_frame), signal_history_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (signal_history_alignment), 0, 0, 12, 0);

  signal_databox = gacx_signal_databox_create ("signal_databox", "", "", 0, 0);
  gtk_widget_set_name (signal_databox, "signal_databox");
  gtk_widget_show (signal_databox);
  gtk_container_add (GTK_CONTAINER (signal_history_alignment), signal_databox);
  GTK_WIDGET_UNSET_FLAGS (signal_databox, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (signal_databox, GTK_CAN_DEFAULT);

  signal_history_label = gtk_label_new (_("<b>Signal History</b>"));
  gtk_widget_set_name (signal_history_label, "signal_history_label");
  gtk_widget_show (signal_history_label);
  gtk_frame_set_label_widget (GTK_FRAME (signal_history_frame), signal_history_label);
  gtk_label_set_use_markup (GTK_LABEL (signal_history_label), TRUE);

  label_tab_signal_history = gtk_label_new (_("Signal History"));
  gtk_widget_set_name (label_tab_signal_history, "label_tab_signal_history");
  gtk_widget_show (label_tab_signal_history);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 2), label_tab_signal_history);

  traffic_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (traffic_frame, "traffic_frame");
  gtk_widget_show (traffic_frame);
  gtk_container_add (GTK_CONTAINER (main_notebook), traffic_frame);

  traffic_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (traffic_alignment, "traffic_alignment");
  gtk_widget_show (traffic_alignment);
  gtk_container_add (GTK_CONTAINER (traffic_frame), traffic_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (traffic_alignment), 0, 0, 12, 0);

  traffic_vbox = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (traffic_vbox, "traffic_vbox");
  gtk_widget_show (traffic_vbox);
  gtk_container_add (GTK_CONTAINER (traffic_alignment), traffic_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (traffic_vbox), 2);

  transmit_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (transmit_vbox, "transmit_vbox");
  gtk_widget_show (transmit_vbox);
  gtk_box_pack_start (GTK_BOX (traffic_vbox), transmit_vbox, TRUE, FALSE, 0);

  transmit_hbox = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (transmit_hbox, "transmit_hbox");
  gtk_widget_show (transmit_hbox);
  gtk_box_pack_start (GTK_BOX (transmit_vbox), transmit_hbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (transmit_hbox), 2);

  transmit_label = gtk_label_new (_("Transmit"));
  gtk_widget_set_name (transmit_label, "transmit_label");
  gtk_widget_show (transmit_label);
  gtk_box_pack_start (GTK_BOX (transmit_hbox), transmit_label, FALSE, FALSE, 0);

  transmit_label_sep = gtk_label_new ("");
  gtk_widget_set_name (transmit_label_sep, "transmit_label_sep");
  gtk_widget_show (transmit_label_sep);
  gtk_box_pack_start (GTK_BOX (transmit_hbox), transmit_label_sep, TRUE, TRUE, 0);

  transmit_entry = gtk_entry_new ();
  gtk_widget_set_name (transmit_entry, "transmit_entry");
  gtk_widget_show (transmit_entry);
  gtk_box_pack_start (GTK_BOX (transmit_hbox), transmit_entry, FALSE, FALSE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (transmit_entry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (transmit_entry), _("0 KB"));
  gtk_entry_set_has_frame (GTK_ENTRY (transmit_entry), FALSE);

  transmit_progressbar = gtk_progress_bar_new ();
  gtk_widget_set_name (transmit_progressbar, "transmit_progressbar");
  gtk_widget_show (transmit_progressbar);
  gtk_box_pack_start (GTK_BOX (transmit_vbox), transmit_progressbar, FALSE, FALSE, 0);
  gtk_progress_bar_set_pulse_step (GTK_PROGRESS_BAR (transmit_progressbar), 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (transmit_progressbar), _("0 Kbps"));

  receive_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (receive_vbox, "receive_vbox");
  gtk_widget_show (receive_vbox);
  gtk_box_pack_start (GTK_BOX (traffic_vbox), receive_vbox, TRUE, FALSE, 0);

  receive_hbox = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (receive_hbox, "receive_hbox");
  gtk_widget_show (receive_hbox);
  gtk_box_pack_start (GTK_BOX (receive_vbox), receive_hbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (receive_hbox), 2);

  receive_label = gtk_label_new (_("Receive"));
  gtk_widget_set_name (receive_label, "receive_label");
  gtk_widget_show (receive_label);
  gtk_box_pack_start (GTK_BOX (receive_hbox), receive_label, FALSE, FALSE, 0);

  receive_label_sep = gtk_label_new ("");
  gtk_widget_set_name (receive_label_sep, "receive_label_sep");
  gtk_widget_show (receive_label_sep);
  gtk_box_pack_start (GTK_BOX (receive_hbox), receive_label_sep, TRUE, TRUE, 0);

  receive_entry = gtk_entry_new ();
  gtk_widget_set_name (receive_entry, "receive_entry");
  gtk_widget_show (receive_entry);
  gtk_box_pack_start (GTK_BOX (receive_hbox), receive_entry, FALSE, FALSE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (receive_entry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (receive_entry), _("0 KB"));
  gtk_entry_set_has_frame (GTK_ENTRY (receive_entry), FALSE);

  receive_progressbar = gtk_progress_bar_new ();
  gtk_widget_set_name (receive_progressbar, "receive_progressbar");
  gtk_widget_show (receive_progressbar);
  gtk_box_pack_start (GTK_BOX (receive_vbox), receive_progressbar, FALSE, FALSE, 0);
  gtk_progress_bar_set_pulse_step (GTK_PROGRESS_BAR (receive_progressbar), 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (receive_progressbar), _("0 Kbps"));

  traffic_label = gtk_label_new (_("<b>Data Rate</b>"));
  gtk_widget_set_name (traffic_label, "traffic_label");
  gtk_widget_show (traffic_label);
  gtk_frame_set_label_widget (GTK_FRAME (traffic_frame), traffic_label);
  gtk_label_set_use_markup (GTK_LABEL (traffic_label), TRUE);

  label_tab_traffic = gtk_label_new (_("Traffic"));
  gtk_widget_set_name (label_tab_traffic, "label_tab_traffic");
  gtk_widget_show (label_tab_traffic);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 3), label_tab_traffic);

  traffic_history_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (traffic_history_frame, "traffic_history_frame");
  gtk_widget_show (traffic_history_frame);
  gtk_container_add (GTK_CONTAINER (main_notebook), traffic_history_frame);

  traffic_history_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (traffic_history_alignment, "traffic_history_alignment");
  gtk_widget_show (traffic_history_alignment);
  gtk_container_add (GTK_CONTAINER (traffic_history_frame), traffic_history_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (traffic_history_alignment), 0, 0, 12, 0);

  traffic_databox = gacx_traffic_databox_create ("traffic_databox", "", "", 0, 0);
  gtk_widget_set_name (traffic_databox, "traffic_databox");
  gtk_widget_show (traffic_databox);
  gtk_container_add (GTK_CONTAINER (traffic_history_alignment), traffic_databox);
  GTK_WIDGET_UNSET_FLAGS (traffic_databox, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (traffic_databox, GTK_CAN_DEFAULT);

  traffic_history_label = gtk_label_new (_("<b>Traffic History</b>"));
  gtk_widget_set_name (traffic_history_label, "traffic_history_label");
  gtk_widget_show (traffic_history_label);
  gtk_frame_set_label_widget (GTK_FRAME (traffic_history_frame), traffic_history_label);
  gtk_label_set_use_markup (GTK_LABEL (traffic_history_label), TRUE);

  label_tab_traffic_history = gtk_label_new (_("Traffic History"));
  gtk_widget_set_name (label_tab_traffic_history, "label_tab_traffic_history");
  gtk_widget_show (label_tab_traffic_history);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 4), label_tab_traffic_history);

  settings_frame = gtk_frame_new (NULL);
  gtk_widget_set_name (settings_frame, "settings_frame");
  gtk_widget_show (settings_frame);
  gtk_container_add (GTK_CONTAINER (main_notebook), settings_frame);

  settings_alignment = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (settings_alignment, "settings_alignment");
  gtk_widget_show (settings_alignment);
  gtk_container_add (GTK_CONTAINER (settings_frame), settings_alignment);
  gtk_alignment_set_padding (GTK_ALIGNMENT (settings_alignment), 0, 0, 12, 0);

  settings_hbox = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (settings_hbox, "settings_hbox");
  gtk_widget_show (settings_hbox);
  gtk_container_add (GTK_CONTAINER (settings_alignment), settings_hbox);
  gtk_container_set_border_width (GTK_CONTAINER (settings_hbox), 2);

  vbox_settings_controls = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (vbox_settings_controls, "vbox_settings_controls");
  gtk_widget_show (vbox_settings_controls);
  gtk_box_pack_start (GTK_BOX (settings_hbox), vbox_settings_controls, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox_settings_controls), 2);

  checkbutton_rate = gtk_check_button_new_with_mnemonic (_("Startup at highest rate"));
  gtk_widget_set_name (checkbutton_rate, "checkbutton_rate");
  gtk_widget_show (checkbutton_rate);
  gtk_box_pack_start (GTK_BOX (vbox_settings_controls), checkbutton_rate, FALSE, FALSE, 0);

  table_settings = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table_settings, "table_settings");
  gtk_widget_show (table_settings);
  gtk_box_pack_start (GTK_BOX (vbox_settings_controls), table_settings, TRUE, TRUE, 0);
  gtk_table_set_col_spacings (GTK_TABLE (table_settings), 2);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox16, "vbox16");
  gtk_widget_show (vbox16);
  gtk_table_attach (GTK_TABLE (table_settings), vbox16, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox11, "hbox11");
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox11, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("Channel scan period (ms)"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox11), label6, FALSE, FALSE, 0);

  hscale_channel = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (100, 100, 2000, 1, 1, 0)));
  gtk_widget_set_name (hscale_channel, "hscale_channel");
  gtk_widget_show (hscale_channel);
  gtk_box_pack_start (GTK_BOX (vbox16), hscale_channel, TRUE, TRUE, 0);
  gtk_scale_set_draw_value (GTK_SCALE (hscale_channel), FALSE);
  gtk_scale_set_value_pos (GTK_SCALE (hscale_channel), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (hscale_channel), 0);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox17, "vbox17");
  gtk_widget_show (vbox17);
  gtk_table_attach (GTK_TABLE (table_settings), vbox17, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox12, "hbox12");
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox17), hbox12, TRUE, TRUE, 0);

  label7 = gtk_label_new (_("Min packets before rate-up"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox12), label7, FALSE, FALSE, 0);

  hscale_packets = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (5, 5, 1200, 1, 1, 0)));
  gtk_widget_set_name (hscale_packets, "hscale_packets");
  gtk_widget_show (hscale_packets);
  gtk_box_pack_start (GTK_BOX (vbox17), hscale_packets, TRUE, TRUE, 0);
  gtk_scale_set_draw_value (GTK_SCALE (hscale_packets), FALSE);
  gtk_scale_set_value_pos (GTK_SCALE (hscale_packets), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (hscale_packets), 0);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox18, "vbox18");
  gtk_widget_show (vbox18);
  gtk_table_attach (GTK_TABLE (table_settings), vbox18, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox18), hbox13, TRUE, TRUE, 0);

  label8 = gtk_label_new (_("Min seconds before rate-up"));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox13), label8, FALSE, FALSE, 0);

  hscale_seconds_min = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (5, 5, 1199, 1, 1, 0)));
  gtk_widget_set_name (hscale_seconds_min, "hscale_seconds_min");
  gtk_widget_show (hscale_seconds_min);
  gtk_box_pack_start (GTK_BOX (vbox18), hscale_seconds_min, TRUE, TRUE, 0);
  gtk_scale_set_draw_value (GTK_SCALE (hscale_seconds_min), FALSE);
  gtk_scale_set_value_pos (GTK_SCALE (hscale_seconds_min), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (hscale_seconds_min), 0);

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox19, "vbox19");
  gtk_widget_show (vbox19);
  gtk_table_attach (GTK_TABLE (table_settings), vbox19, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox14, "hbox14");
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox19), hbox14, TRUE, TRUE, 0);

  label9 = gtk_label_new (_("Max seconds before rate-up"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox14), label9, FALSE, FALSE, 0);

  hscale_seconds_max = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (6, 6, 1200, 1, 1, 0)));
  gtk_widget_set_name (hscale_seconds_max, "hscale_seconds_max");
  gtk_widget_show (hscale_seconds_max);
  gtk_box_pack_start (GTK_BOX (vbox19), hscale_seconds_max, TRUE, TRUE, 0);
  gtk_scale_set_draw_value (GTK_SCALE (hscale_seconds_max), FALSE);
  gtk_scale_set_value_pos (GTK_SCALE (hscale_seconds_max), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (hscale_seconds_max), 0);

  alignment3 = gtk_alignment_new (0, 1, 1, 0);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_table_attach (GTK_TABLE (table_settings), alignment3, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  spinbutton_packets_adj = gtk_adjustment_new (5, 5, 1200, 1, 1, 0);
  spinbutton_packets = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_packets_adj), 1, 0);
  gtk_widget_set_name (spinbutton_packets, "spinbutton_packets");
  gtk_widget_show (spinbutton_packets);
  gtk_container_add (GTK_CONTAINER (alignment3), spinbutton_packets);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_packets), TRUE);

  alignment4 = gtk_alignment_new (0, 1, 1, 0);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_table_attach (GTK_TABLE (table_settings), alignment4, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  spinbutton_seconds_min_adj = gtk_adjustment_new (5, 5, 1199, 1, 1, 0);
  spinbutton_seconds_min = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_seconds_min_adj), 1, 0);
  gtk_widget_set_name (spinbutton_seconds_min, "spinbutton_seconds_min");
  gtk_widget_show (spinbutton_seconds_min);
  gtk_container_add (GTK_CONTAINER (alignment4), spinbutton_seconds_min);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_seconds_min), TRUE);

  alignment5 = gtk_alignment_new (0, 1, 1, 0);
  gtk_widget_set_name (alignment5, "alignment5");
  gtk_widget_show (alignment5);
  gtk_table_attach (GTK_TABLE (table_settings), alignment5, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  spinbutton_seconds_max_adj = gtk_adjustment_new (6, 6, 1200, 1, 1, 0);
  spinbutton_seconds_max = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_seconds_max_adj), 1, 0);
  gtk_widget_set_name (spinbutton_seconds_max, "spinbutton_seconds_max");
  gtk_widget_show (spinbutton_seconds_max);
  gtk_container_add (GTK_CONTAINER (alignment5), spinbutton_seconds_max);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_seconds_max), TRUE);

  alignment_channel = gtk_alignment_new (0, 1, 1, 0);
  gtk_widget_set_name (alignment_channel, "alignment_channel");
  gtk_widget_show (alignment_channel);
  gtk_table_attach (GTK_TABLE (table_settings), alignment_channel, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  spinbutton_channel_adj = gtk_adjustment_new (100, 100, 2000, 1, 1, 0);
  spinbutton_channel = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_channel_adj), 1, 0);
  gtk_widget_set_name (spinbutton_channel, "spinbutton_channel");
  gtk_widget_show (spinbutton_channel);
  gtk_container_add (GTK_CONTAINER (alignment_channel), spinbutton_channel);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_channel), TRUE);

  vbox_settings_buttons = gtk_vbox_new (FALSE, 2);
  gtk_widget_set_name (vbox_settings_buttons, "vbox_settings_buttons");
  gtk_widget_show (vbox_settings_buttons);
  gtk_box_pack_start (GTK_BOX (settings_hbox), vbox_settings_buttons, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox_settings_buttons), 2);

  label_button_space = gtk_label_new ("");
  gtk_widget_set_name (label_button_space, "label_button_space");
  gtk_widget_show (label_button_space);
  gtk_box_pack_start (GTK_BOX (vbox_settings_buttons), label_button_space, TRUE, TRUE, 0);

  button_apply = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_set_name (button_apply, "button_apply");
  gtk_widget_show (button_apply);
  gtk_box_pack_start (GTK_BOX (vbox_settings_buttons), button_apply, FALSE, FALSE, 0);

  button_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (button_cancel, "button_cancel");
  gtk_widget_show (button_cancel);
  gtk_box_pack_start (GTK_BOX (vbox_settings_buttons), button_cancel, FALSE, FALSE, 0);

  settings_label = gtk_label_new (_("<b>Settings</b>"));
  gtk_widget_set_name (settings_label, "settings_label");
  gtk_widget_show (settings_label);
  gtk_frame_set_label_widget (GTK_FRAME (settings_frame), settings_label);
  gtk_label_set_use_markup (GTK_LABEL (settings_label), TRUE);

  label_tab_settings = gtk_label_new (_("Settings"));
  gtk_widget_set_name (label_tab_settings, "label_tab_settings");
  gtk_widget_show (label_tab_settings);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 5), label_tab_settings);

  about_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (about_vbox, "about_vbox");
  gtk_widget_show (about_vbox);
  gtk_container_add (GTK_CONTAINER (main_notebook), about_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (about_vbox), 6);

  about_image = create_pixmap (main_window, "gacxtool.png");
  gtk_widget_set_name (about_image, "about_image");
  gtk_widget_show (about_image);
  gtk_box_pack_start (GTK_BOX (about_vbox), about_image, FALSE, FALSE, 10);

  label_about_title = gtk_label_new (_("<span size=\"x-large\"><b>GTK ACX Tool 0.0.0</b></span>"));
  gtk_widget_set_name (label_about_title, "label_about_title");
  gtk_widget_show (label_about_title);
  gtk_box_pack_start (GTK_BOX (about_vbox), label_about_title, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (label_about_title, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label_about_title), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_about_title), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label_about_title), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label_about_title), TRUE);

  label_about_info = gtk_label_new (_("The GTK ACX Tool displays the status of a ACX driver."));
  gtk_widget_set_name (label_about_info, "label_about_info");
  gtk_widget_show (label_about_info);
  gtk_box_pack_start (GTK_BOX (about_vbox), label_about_info, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (label_about_info, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label_about_info), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_about_info), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label_about_info), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label_about_info), TRUE);

  label_about_copyright = gtk_label_new (_("<span size=\"x-small\">(C) 2004 Leonid Zolotarev</span>"));
  gtk_widget_set_name (label_about_copyright, "label_about_copyright");
  gtk_widget_show (label_about_copyright);
  gtk_box_pack_start (GTK_BOX (about_vbox), label_about_copyright, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (label_about_copyright, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label_about_copyright), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_about_copyright), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label_about_copyright), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label_about_copyright), TRUE);

  label_tab_about = gtk_label_new (_("About"));
  gtk_widget_set_name (label_tab_about, "label_tab_about");
  gtk_widget_show (label_tab_about);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 6), label_tab_about);

  main_hpaned = gtk_hpaned_new ();
  gtk_widget_set_name (main_hpaned, "main_hpaned");
  gtk_widget_show (main_hpaned);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_hpaned, FALSE, FALSE, 0);

  device_statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (device_statusbar, "device_statusbar");
  gtk_widget_show (device_statusbar);
  gtk_paned_pack1 (GTK_PANED (main_hpaned), device_statusbar, FALSE, TRUE);
  gtk_widget_set_size_request (device_statusbar, 99, -1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (device_statusbar), FALSE);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_set_name (hpaned1, "hpaned1");
  gtk_widget_show (hpaned1);
  gtk_paned_pack2 (GTK_PANED (main_hpaned), hpaned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (hpaned1), 0);

  main_statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (main_statusbar, "main_statusbar");
  gtk_widget_show (main_statusbar);
  gtk_paned_pack1 (GTK_PANED (hpaned1), main_statusbar, TRUE, FALSE);
  gtk_widget_set_size_request (main_statusbar, 160, -1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (main_statusbar), FALSE);

  user_statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (user_statusbar, "user_statusbar");
  gtk_widget_show (user_statusbar);
  gtk_paned_pack2 (GTK_PANED (hpaned1), user_statusbar, TRUE, FALSE);
  gtk_widget_set_size_request (user_statusbar, 215, -1);

  g_signal_connect ((gpointer) main_window, "destroy",
                    G_CALLBACK (on_main_window_destroy),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_rate, "toggled",
                    G_CALLBACK (on_checkbutton_rate_toggled),
                    NULL);
  g_signal_connect ((gpointer) hscale_channel, "value_changed",
                    G_CALLBACK (on_hscale_channel_value_changed),
                    NULL);
  g_signal_connect ((gpointer) hscale_packets, "value_changed",
                    G_CALLBACK (on_hscale_packets_value_changed),
                    NULL);
  g_signal_connect ((gpointer) hscale_seconds_min, "value_changed",
                    G_CALLBACK (on_hscale_seconds_min_value_changed),
                    NULL);
  g_signal_connect ((gpointer) hscale_seconds_max, "value_changed",
                    G_CALLBACK (on_hscale_seconds_max_value_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_packets, "value_changed",
                    G_CALLBACK (on_spinbutton_packets_value_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_seconds_min, "value_changed",
                    G_CALLBACK (on_spinbutton_seconds_min_value_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_seconds_max, "value_changed",
                    G_CALLBACK (on_spinbutton_seconds_max_value_changed),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_channel, "value_changed",
                    G_CALLBACK (on_spinbutton_channel_value_changed),
                    NULL);
  g_signal_connect ((gpointer) button_apply, "clicked",
                    G_CALLBACK (on_button_apply_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cancel, "clicked",
                    G_CALLBACK (on_button_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, main_vbox, "main_vbox");
  GLADE_HOOKUP_OBJECT (main_window, main_notebook, "main_notebook");
  GLADE_HOOKUP_OBJECT (main_window, link_frame, "link_frame");
  GLADE_HOOKUP_OBJECT (main_window, link_alignment, "link_alignment");
  GLADE_HOOKUP_OBJECT (main_window, link_table, "link_table");
  GLADE_HOOKUP_OBJECT (main_window, entry_status, "entry_status");
  GLADE_HOOKUP_OBJECT (main_window, entry_bssid, "entry_bssid");
  GLADE_HOOKUP_OBJECT (main_window, entry_ssid, "entry_ssid");
  GLADE_HOOKUP_OBJECT (main_window, entry_channel, "entry_channel");
  GLADE_HOOKUP_OBJECT (main_window, label_bssid, "label_bssid");
  GLADE_HOOKUP_OBJECT (main_window, label_status, "label_status");
  GLADE_HOOKUP_OBJECT (main_window, label_ssid, "label_ssid");
  GLADE_HOOKUP_OBJECT (main_window, label_channel, "label_channel");
  GLADE_HOOKUP_OBJECT (main_window, hbox_txrate, "hbox_txrate");
  GLADE_HOOKUP_OBJECT (main_window, frame_rate_1, "frame_rate_1");
  GLADE_HOOKUP_OBJECT (main_window, eventbox_rate_1, "eventbox_rate_1");
  GLADE_HOOKUP_OBJECT (main_window, label_rate_1, "label_rate_1");
  GLADE_HOOKUP_OBJECT (main_window, frame_rate_2, "frame_rate_2");
  GLADE_HOOKUP_OBJECT (main_window, eventbox_rate_2, "eventbox_rate_2");
  GLADE_HOOKUP_OBJECT (main_window, label_rate_2, "label_rate_2");
  GLADE_HOOKUP_OBJECT (main_window, frame_rate_5, "frame_rate_5");
  GLADE_HOOKUP_OBJECT (main_window, eventbox_rate_5, "eventbox_rate_5");
  GLADE_HOOKUP_OBJECT (main_window, label_rate_5, "label_rate_5");
  GLADE_HOOKUP_OBJECT (main_window, frame_rate_11, "frame_rate_11");
  GLADE_HOOKUP_OBJECT (main_window, eventbox_rate_11, "eventbox_rate_11");
  GLADE_HOOKUP_OBJECT (main_window, label_rate_11, "label_rate_11");
  GLADE_HOOKUP_OBJECT (main_window, frame_rate_22, "frame_rate_22");
  GLADE_HOOKUP_OBJECT (main_window, eventbox_rate_22, "eventbox_rate_22");
  GLADE_HOOKUP_OBJECT (main_window, label_rate_22, "label_rate_22");
  GLADE_HOOKUP_OBJECT (main_window, label_txrate, "label_txrate");
  GLADE_HOOKUP_OBJECT (main_window, link_label, "link_label");
  GLADE_HOOKUP_OBJECT (main_window, label_tab_link, "label_tab_link");
  GLADE_HOOKUP_OBJECT (main_window, signal_frame, "signal_frame");
  GLADE_HOOKUP_OBJECT (main_window, signal_alignment, "signal_alignment");
  GLADE_HOOKUP_OBJECT (main_window, signal_vbox, "signal_vbox");
  GLADE_HOOKUP_OBJECT (main_window, quality_vbox, "quality_vbox");
  GLADE_HOOKUP_OBJECT (main_window, quality_hbox, "quality_hbox");
  GLADE_HOOKUP_OBJECT (main_window, quality_label, "quality_label");
  GLADE_HOOKUP_OBJECT (main_window, quality_progressbar, "quality_progressbar");
  GLADE_HOOKUP_OBJECT (main_window, strength_vbox, "strength_vbox");
  GLADE_HOOKUP_OBJECT (main_window, strength_hbox, "strength_hbox");
  GLADE_HOOKUP_OBJECT (main_window, strength_label, "strength_label");
  GLADE_HOOKUP_OBJECT (main_window, strength_label_sep, "strength_label_sep");
  GLADE_HOOKUP_OBJECT (main_window, strength_entry, "strength_entry");
  GLADE_HOOKUP_OBJECT (main_window, strength_label_avg, "strength_label_avg");
  GLADE_HOOKUP_OBJECT (main_window, strength_entry_avg, "strength_entry_avg");
  GLADE_HOOKUP_OBJECT (main_window, strength_label_max, "strength_label_max");
  GLADE_HOOKUP_OBJECT (main_window, strength_entry_max, "strength_entry_max");
  GLADE_HOOKUP_OBJECT (main_window, strength_progressbar, "strength_progressbar");
  GLADE_HOOKUP_OBJECT (main_window, noise_vbox, "noise_vbox");
  GLADE_HOOKUP_OBJECT (main_window, noise_hbox, "noise_hbox");
  GLADE_HOOKUP_OBJECT (main_window, noise_label, "noise_label");
  GLADE_HOOKUP_OBJECT (main_window, noise_label_sep, "noise_label_sep");
  GLADE_HOOKUP_OBJECT (main_window, noise_entry, "noise_entry");
  GLADE_HOOKUP_OBJECT (main_window, noise_label_avg, "noise_label_avg");
  GLADE_HOOKUP_OBJECT (main_window, noise_entry_avg, "noise_entry_avg");
  GLADE_HOOKUP_OBJECT (main_window, noise_label_max, "noise_label_max");
  GLADE_HOOKUP_OBJECT (main_window, noise_entry_max, "noise_entry_max");
  GLADE_HOOKUP_OBJECT (main_window, noise_progressbar, "noise_progressbar");
  GLADE_HOOKUP_OBJECT (main_window, signal_label, "signal_label");
  GLADE_HOOKUP_OBJECT (main_window, label_tab_signal, "label_tab_signal");
  GLADE_HOOKUP_OBJECT (main_window, signal_history_frame, "signal_history_frame");
  GLADE_HOOKUP_OBJECT (main_window, signal_history_alignment, "signal_history_alignment");
  GLADE_HOOKUP_OBJECT (main_window, signal_databox, "signal_databox");
  GLADE_HOOKUP_OBJECT (main_window, signal_history_label, "signal_history_label");
  GLADE_HOOKUP_OBJECT (main_window, label_tab_signal_history, "label_tab_signal_history");
  GLADE_HOOKUP_OBJECT (main_window, traffic_frame, "traffic_frame");
  GLADE_HOOKUP_OBJECT (main_window, traffic_alignment, "traffic_alignment");
  GLADE_HOOKUP_OBJECT (main_window, traffic_vbox, "traffic_vbox");
  GLADE_HOOKUP_OBJECT (main_window, transmit_vbox, "transmit_vbox");
  GLADE_HOOKUP_OBJECT (main_window, transmit_hbox, "transmit_hbox");
  GLADE_HOOKUP_OBJECT (main_window, transmit_label, "transmit_label");
  GLADE_HOOKUP_OBJECT (main_window, transmit_label_sep, "transmit_label_sep");
  GLADE_HOOKUP_OBJECT (main_window, transmit_entry, "transmit_entry");
  GLADE_HOOKUP_OBJECT (main_window, transmit_progressbar, "transmit_progressbar");
  GLADE_HOOKUP_OBJECT (main_window, receive_vbox, "receive_vbox");
  GLADE_HOOKUP_OBJECT (main_window, receive_hbox, "receive_hbox");
  GLADE_HOOKUP_OBJECT (main_window, receive_label, "receive_label");
  GLADE_HOOKUP_OBJECT (main_window, receive_label_sep, "receive_label_sep");
  GLADE_HOOKUP_OBJECT (main_window, receive_entry, "receive_entry");
  GLADE_HOOKUP_OBJECT (main_window, receive_progressbar, "receive_progressbar");
  GLADE_HOOKUP_OBJECT (main_window, traffic_label, "traffic_label");
  GLADE_HOOKUP_OBJECT (main_window, label_tab_traffic, "label_tab_traffic");
  GLADE_HOOKUP_OBJECT (main_window, traffic_history_frame, "traffic_history_frame");
  GLADE_HOOKUP_OBJECT (main_window, traffic_history_alignment, "traffic_history_alignment");
  GLADE_HOOKUP_OBJECT (main_window, traffic_databox, "traffic_databox");
  GLADE_HOOKUP_OBJECT (main_window, traffic_history_label, "traffic_history_label");
  GLADE_HOOKUP_OBJECT (main_window, label_tab_traffic_history, "label_tab_traffic_history");
  GLADE_HOOKUP_OBJECT (main_window, settings_frame, "settings_frame");
  GLADE_HOOKUP_OBJECT (main_window, settings_alignment, "settings_alignment");
  GLADE_HOOKUP_OBJECT (main_window, settings_hbox, "settings_hbox");
  GLADE_HOOKUP_OBJECT (main_window, vbox_settings_controls, "vbox_settings_controls");
  GLADE_HOOKUP_OBJECT (main_window, checkbutton_rate, "checkbutton_rate");
  GLADE_HOOKUP_OBJECT (main_window, table_settings, "table_settings");
  GLADE_HOOKUP_OBJECT (main_window, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (main_window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (main_window, label6, "label6");
  GLADE_HOOKUP_OBJECT (main_window, hscale_channel, "hscale_channel");
  GLADE_HOOKUP_OBJECT (main_window, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (main_window, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (main_window, label7, "label7");
  GLADE_HOOKUP_OBJECT (main_window, hscale_packets, "hscale_packets");
  GLADE_HOOKUP_OBJECT (main_window, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (main_window, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (main_window, label8, "label8");
  GLADE_HOOKUP_OBJECT (main_window, hscale_seconds_min, "hscale_seconds_min");
  GLADE_HOOKUP_OBJECT (main_window, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (main_window, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (main_window, label9, "label9");
  GLADE_HOOKUP_OBJECT (main_window, hscale_seconds_max, "hscale_seconds_max");
  GLADE_HOOKUP_OBJECT (main_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (main_window, spinbutton_packets, "spinbutton_packets");
  GLADE_HOOKUP_OBJECT (main_window, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (main_window, spinbutton_seconds_min, "spinbutton_seconds_min");
  GLADE_HOOKUP_OBJECT (main_window, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (main_window, spinbutton_seconds_max, "spinbutton_seconds_max");
  GLADE_HOOKUP_OBJECT (main_window, alignment_channel, "alignment_channel");
  GLADE_HOOKUP_OBJECT (main_window, spinbutton_channel, "spinbutton_channel");
  GLADE_HOOKUP_OBJECT (main_window, vbox_settings_buttons, "vbox_settings_buttons");
  GLADE_HOOKUP_OBJECT (main_window, label_button_space, "label_button_space");
  GLADE_HOOKUP_OBJECT (main_window, button_apply, "button_apply");
  GLADE_HOOKUP_OBJECT (main_window, button_cancel, "button_cancel");
  GLADE_HOOKUP_OBJECT (main_window, settings_label, "settings_label");
  GLADE_HOOKUP_OBJECT (main_window, label_tab_settings, "label_tab_settings");
  GLADE_HOOKUP_OBJECT (main_window, about_vbox, "about_vbox");
  GLADE_HOOKUP_OBJECT (main_window, about_image, "about_image");
  GLADE_HOOKUP_OBJECT (main_window, label_about_title, "label_about_title");
  GLADE_HOOKUP_OBJECT (main_window, label_about_info, "label_about_info");
  GLADE_HOOKUP_OBJECT (main_window, label_about_copyright, "label_about_copyright");
  GLADE_HOOKUP_OBJECT (main_window, label_tab_about, "label_tab_about");
  GLADE_HOOKUP_OBJECT (main_window, main_hpaned, "main_hpaned");
  GLADE_HOOKUP_OBJECT (main_window, device_statusbar, "device_statusbar");
  GLADE_HOOKUP_OBJECT (main_window, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (main_window, main_statusbar, "main_statusbar");
  GLADE_HOOKUP_OBJECT (main_window, user_statusbar, "user_statusbar");

  return main_window;
}

GtkWidget*
create_main_dialog (void)
{
  GtkWidget *main_dialog;
  GdkPixbuf *main_dialog_icon_pixbuf;
  GtkWidget *dialog_vbox_privileges;
  GtkWidget *hbox_privileges;
  GtkWidget *image_privileges;
  GtkWidget *vbox_privileges;
  GtkWidget *hbox_admin;
  GtkWidget *label_admin;
  GtkWidget *hbox_root;
  GtkWidget *label_root;
  GtkWidget *dialog_action_area_privileges;
  GtkWidget *ok_button_privileges;

  main_dialog = gtk_dialog_new ();
  gtk_widget_set_name (main_dialog, "main_dialog");
  gtk_window_set_title (GTK_WINDOW (main_dialog), _("Insufficient privileges"));
  gtk_window_set_position (GTK_WINDOW (main_dialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (main_dialog), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (main_dialog), FALSE);
  main_dialog_icon_pixbuf = create_pixbuf ("gacxtool.png");
  if (main_dialog_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (main_dialog), main_dialog_icon_pixbuf);
      gdk_pixbuf_unref (main_dialog_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (main_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox_privileges = GTK_DIALOG (main_dialog)->vbox;
  gtk_widget_set_name (dialog_vbox_privileges, "dialog_vbox_privileges");
  gtk_widget_show (dialog_vbox_privileges);

  hbox_privileges = gtk_hbox_new (FALSE, 12);
  gtk_widget_set_name (hbox_privileges, "hbox_privileges");
  gtk_widget_show (hbox_privileges);
  gtk_box_pack_start (GTK_BOX (dialog_vbox_privileges), hbox_privileges, TRUE, TRUE, 0);

  image_privileges = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_DIALOG);
  gtk_widget_set_name (image_privileges, "image_privileges");
  gtk_widget_show (image_privileges);
  gtk_box_pack_start (GTK_BOX (hbox_privileges), image_privileges, FALSE, FALSE, 0);

  vbox_privileges = gtk_vbox_new (FALSE, 12);
  gtk_widget_set_name (vbox_privileges, "vbox_privileges");
  gtk_widget_show (vbox_privileges);
  gtk_box_pack_start (GTK_BOX (hbox_privileges), vbox_privileges, TRUE, TRUE, 0);

  hbox_admin = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox_admin, "hbox_admin");
  gtk_widget_show (hbox_admin);
  gtk_box_pack_start (GTK_BOX (vbox_privileges), hbox_admin, FALSE, FALSE, 0);

  label_admin = gtk_label_new (_("<span size=\"large\"><b>To change these variables,\nyou need administrator privileges</b></span>"));
  gtk_widget_set_name (label_admin, "label_admin");
  gtk_widget_show (label_admin);
  gtk_box_pack_start (GTK_BOX (hbox_admin), label_admin, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_admin), TRUE);

  hbox_root = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox_root, "hbox_root");
  gtk_widget_show (hbox_root);
  gtk_box_pack_start (GTK_BOX (vbox_privileges), hbox_root, FALSE, FALSE, 0);

  label_root = gtk_label_new (_("To acquire such privileges, login as root."));
  gtk_widget_set_name (label_root, "label_root");
  gtk_widget_show (label_root);
  gtk_box_pack_start (GTK_BOX (hbox_root), label_root, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label_root), TRUE);

  dialog_action_area_privileges = GTK_DIALOG (main_dialog)->action_area;
  gtk_widget_set_name (dialog_action_area_privileges, "dialog_action_area_privileges");
  gtk_widget_show (dialog_action_area_privileges);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area_privileges), GTK_BUTTONBOX_END);

  ok_button_privileges = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (ok_button_privileges, "ok_button_privileges");
  gtk_widget_show (ok_button_privileges);
  gtk_dialog_add_action_widget (GTK_DIALOG (main_dialog), ok_button_privileges, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_button_privileges, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) ok_button_privileges, "clicked",
                    G_CALLBACK (on_ok_button_privileges_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_dialog, main_dialog, "main_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (main_dialog, dialog_vbox_privileges, "dialog_vbox_privileges");
  GLADE_HOOKUP_OBJECT (main_dialog, hbox_privileges, "hbox_privileges");
  GLADE_HOOKUP_OBJECT (main_dialog, image_privileges, "image_privileges");
  GLADE_HOOKUP_OBJECT (main_dialog, vbox_privileges, "vbox_privileges");
  GLADE_HOOKUP_OBJECT (main_dialog, hbox_admin, "hbox_admin");
  GLADE_HOOKUP_OBJECT (main_dialog, label_admin, "label_admin");
  GLADE_HOOKUP_OBJECT (main_dialog, hbox_root, "hbox_root");
  GLADE_HOOKUP_OBJECT (main_dialog, label_root, "label_root");
  GLADE_HOOKUP_OBJECT_NO_REF (main_dialog, dialog_action_area_privileges, "dialog_action_area_privileges");
  GLADE_HOOKUP_OBJECT (main_dialog, ok_button_privileges, "ok_button_privileges");

  return main_dialog;
}

